name: Code Formatting
on: [push, pull_request]
jobs:
  python-linter:
    name: Python
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: python-linter
        uses: piotrpawlaczek/python-blacken@v20.8b1
