name: Code Formatting
on: [push, pull_request]
jobs:
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    - name: Python Blacken
      uses: piotrpawlaczek/python-blacken@v20.8b1
